from django.urls import path

from practice.views import (
    AttemptView,
    BookView,
    MatchActView,
    MatchAskView,
    MatchDebriefView,
    MatchDepartureView,
    MatchDetailView,
    MatchIntentView,
    MatchListView,
    MatchNextView,
    MatchReadsView,
    MatchResignView,
    PlaybookDetailView,
    PlaybookListView,
    PlaybookVocabularyView,
    ProfileView,
    ReviewView,
    SetDetailView,
    SetListView,
    TableActView,
    TableDetailView,
    TableListView,
    TableNextView,
    TestAnswerView,
    TestDetailView,
    TestEndView,
    TestListView,
    TestNextView,
    TodaySetView,
)

urlpatterns = [
    path("profile/", ProfileView.as_view(), name="practice-profile"),
    path("sets/", SetListView.as_view(), name="practice-sets"),
    path("sets/today/", TodaySetView.as_view(), name="practice-today"),
    path("sets/<int:pk>/", SetDetailView.as_view(), name="practice-set"),
    path("attempts/", AttemptView.as_view(), name="practice-attempts"),
    path("reviews/", ReviewView.as_view(), name="practice-reviews"),
    path("playbooks/", PlaybookListView.as_view(), name="practice-playbooks"),
    path("playbooks/vocabulary/", PlaybookVocabularyView.as_view(), name="practice-playbook-vocabulary"),
    path("playbooks/<int:pk>/", PlaybookDetailView.as_view(), name="practice-playbook"),
    path("hands/by-the-book/", BookView.as_view(), name="practice-by-the-book"),
    path("matches/", MatchListView.as_view(), name="practice-matches"),
    path("matches/<int:pk>/", MatchDetailView.as_view(), name="practice-match"),
    path("matches/<int:pk>/act/", MatchActView.as_view(), name="practice-match-act"),
    path("matches/<int:pk>/intent/", MatchIntentView.as_view(), name="practice-match-intent"),
    path("matches/<int:pk>/ask/", MatchAskView.as_view(), name="practice-match-ask"),
    path("matches/<int:pk>/next/", MatchNextView.as_view(), name="practice-match-next"),
    path("matches/<int:pk>/resign/", MatchResignView.as_view(), name="practice-match-resign"),
    path("matches/<int:pk>/departure/", MatchDepartureView.as_view(), name="practice-match-departure"),
    path("matches/<int:pk>/reads/", MatchReadsView.as_view(), name="practice-match-reads"),
    path("matches/<int:pk>/debrief/", MatchDebriefView.as_view(), name="practice-match-debrief"),
    path("tests/", TestListView.as_view(), name="practice-tests"),
    path("tests/<int:pk>/", TestDetailView.as_view(), name="practice-test"),
    path("tests/<int:pk>/next/", TestNextView.as_view(), name="practice-test-next"),
    path("tests/<int:pk>/answer/", TestAnswerView.as_view(), name="practice-test-answer"),
    path("tests/<int:pk>/end/", TestEndView.as_view(), name="practice-test-end"),
    path("tables/", TableListView.as_view(), name="practice-tables"),
    path("tables/<int:pk>/", TableDetailView.as_view(), name="practice-table"),
    path("tables/<int:pk>/act/", TableActView.as_view(), name="practice-table-act"),
    path("tables/<int:pk>/next/", TableNextView.as_view(), name="practice-table-next"),
]
