# Generated by Django 6.0.5 on 2026-05-23 02:51

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfirmEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "confirm_code",
                    models.CharField(max_length=6, verbose_name="Verification code"),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "profile_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Profile name"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Profile tag"
                    ),
                ),
                (
                    "username_changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Profile tag changed at",
                    ),
                ),
                (
                    "bio",
                    models.CharField(
                        default="", max_length=255, verbose_name="Bio"
                    ),
                ),
                (
                    "profile_image_url",
                    models.URLField(
                        blank=True,
                        default=None,
                        max_length=2048,
                        null=True,
                        verbose_name="Profile image URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Joined at"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last login at"
                    ),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Password changed at",
                    ),
                ),
                (
                    "deletion_requested_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletion requested at"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False, verbose_name="Is system admin"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Is staff"),
                ),
                (
                    "is_customer",
                    models.BooleanField(default=True, verbose_name="Is customer"),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="SocialLoginIdentifier",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google"), ("apple", "Apple")],
                        max_length=10,
                        verbose_name="Social login provider",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                ("temp_access_token", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
