# Generated by Django 6.0.5 on 2026-05-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmemail',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Profile tag'),
        ),
        migrations.AddIndex(
            model_name='confirmemail',
            index=models.Index(fields=['email', '-created'], name='idx_confirmemail_email_created'),
        ),
    ]
