# Generated by Django 6.1.1 on 2026-10-03 17:42

from django.conf import settings
from django.db import migrations


def create_missing_client_tokens(apps, schema_editor):
    """Give users created before client tokens existed one too."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    ClientToken = apps.get_model("users", "ClientToken")
    users = User.objects.filter(client_token__isnull=True)
    # Each instance calls the field's default, so every key is different.
    ClientToken.objects.bulk_create(ClientToken(user=user) for user in users)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_missing_client_tokens, migrations.RunPython.noop),
    ]
