# Generated by Django 6.0.5 on 2026-05-24 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_username_unique_and_confirmemail_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Username"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username_changed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Username changed at"
            ),
        ),
    ]
