# Generated by OpenCode on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_username_alter_user_username_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="client_token_hash",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Client token hash",
            ),
        ),
    ]
