# Generated by OpenCode on 2026-06-03

from django.db import migrations, models


def normalize_client_token_hashes(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.exclude(client_token_hash__isnull=True).exclude(
        client_token_hash=""
    ):
        normalized = user.client_token_hash.lower()
        if user.client_token_hash != normalized:
            user.client_token_hash = normalized
            user.save(update_fields=["client_token_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_client_token_hash"),
    ]

    operations = [
        migrations.RunPython(normalize_client_token_hashes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="client_token_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Client token hash",
            ),
        ),
    ]
