[project]
name = "pokerland-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cryptography>=48.0.0",
    "django-cors-headers>=4.9.0",
    "django-extensions>=4.1",
    "djangorestframework>=3.17.1",
    "djangorestframework-stubs>=3.17.0",
    "drf-yasg>=1.21.15",
    "factory-boy>=3.3.3",
    "firebase-admin>=7.4.0",
    "google-api-python-client>=2.196.0",
    "psycopg2-binary>=2.9.12",
]

[dependency-groups]
dev = [
    "ruff>=0.15.14",
]
