# Generated by Django 6.0.5 on 2026-05-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authtoken",
            name="token_key",
            field=models.CharField(
                db_index=True,
                help_text="Partial token value stored in DB to avoid exposing full token if compromised.",
                max_length=128,
            ),
        ),
    ]
