# Generated by Django 6.1.1 on 2026-10-06 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(max_length=32)),
                ("hand_id", models.CharField(max_length=32)),
                ("played_at", models.DateTimeField()),
                ("game", models.CharField(max_length=64)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("play_money", models.BooleanField(default=False)),
                ("small_blind", models.BigIntegerField()),
                ("big_blind", models.BigIntegerField()),
                ("tournament_id", models.CharField(blank=True, max_length=32)),
                ("table", models.CharField(max_length=64)),
                ("hero", models.CharField(blank=True, max_length=64)),
                ("hero_position", models.CharField(blank=True, max_length=8)),
                ("hero_cards", models.JSONField(blank=True, default=list)),
                ("hero_net", models.BigIntegerField(default=0)),
                ("final_street", models.CharField(max_length=32)),
                ("replay", models.JSONField(default=dict)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hands",
                        to="tracker.logstream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-played_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["user", "-played_at", "-id"], name="hand_history"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "site", "hand_id"), name="unique_hand_per_user"
                    )
                ],
            },
        ),
    ]
