# Generated by Django 6.1.1 on 2026-10-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="phh",
            field=models.TextField(blank=True),
        ),
    ]
