# Generated by Django 6.1.1 on 2026-10-07 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0002_hand_phh"),
        ("tracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HandPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=64)),
                ("is_hero", models.BooleanField(default=False)),
                ("position", models.CharField(max_length=8)),
                ("stack_bb", models.FloatField()),
                ("cards", models.JSONField(blank=True, default=list)),
                ("situation", models.CharField(blank=True, max_length=16)),
                ("first_action", models.CharField(blank=True, max_length=8)),
                ("vpip_could", models.PositiveSmallIntegerField(default=0)),
                ("vpip_did", models.PositiveSmallIntegerField(default=0)),
                ("pfr_could", models.PositiveSmallIntegerField(default=0)),
                ("pfr_did", models.PositiveSmallIntegerField(default=0)),
                ("rfi_could", models.PositiveSmallIntegerField(default=0)),
                ("rfi_did", models.PositiveSmallIntegerField(default=0)),
                ("limp_could", models.PositiveSmallIntegerField(default=0)),
                ("limp_did", models.PositiveSmallIntegerField(default=0)),
                ("cold_call_could", models.PositiveSmallIntegerField(default=0)),
                ("cold_call_did", models.PositiveSmallIntegerField(default=0)),
                ("three_bet_could", models.PositiveSmallIntegerField(default=0)),
                ("three_bet_did", models.PositiveSmallIntegerField(default=0)),
                (
                    "fold_to_three_bet_could",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("fold_to_three_bet_did", models.PositiveSmallIntegerField(default=0)),
                ("four_bet_could", models.PositiveSmallIntegerField(default=0)),
                ("four_bet_did", models.PositiveSmallIntegerField(default=0)),
                ("squeeze_could", models.PositiveSmallIntegerField(default=0)),
                ("squeeze_did", models.PositiveSmallIntegerField(default=0)),
                ("steal_could", models.PositiveSmallIntegerField(default=0)),
                ("steal_did", models.PositiveSmallIntegerField(default=0)),
                ("fold_to_steal_could", models.PositiveSmallIntegerField(default=0)),
                ("fold_to_steal_did", models.PositiveSmallIntegerField(default=0)),
                ("call_vs_steal_could", models.PositiveSmallIntegerField(default=0)),
                ("call_vs_steal_did", models.PositiveSmallIntegerField(default=0)),
                (
                    "three_bet_vs_steal_could",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("three_bet_vs_steal_did", models.PositiveSmallIntegerField(default=0)),
                ("bb_defend_could", models.PositiveSmallIntegerField(default=0)),
                ("bb_defend_did", models.PositiveSmallIntegerField(default=0)),
                ("cbet_flop_could", models.PositiveSmallIntegerField(default=0)),
                ("cbet_flop_did", models.PositiveSmallIntegerField(default=0)),
                ("cbet_turn_could", models.PositiveSmallIntegerField(default=0)),
                ("cbet_turn_did", models.PositiveSmallIntegerField(default=0)),
                ("cbet_river_could", models.PositiveSmallIntegerField(default=0)),
                ("cbet_river_did", models.PositiveSmallIntegerField(default=0)),
                (
                    "fold_to_cbet_flop_could",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("fold_to_cbet_flop_did", models.PositiveSmallIntegerField(default=0)),
                (
                    "fold_to_cbet_turn_could",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("fold_to_cbet_turn_did", models.PositiveSmallIntegerField(default=0)),
                (
                    "fold_to_cbet_river_could",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("fold_to_cbet_river_did", models.PositiveSmallIntegerField(default=0)),
                ("donk_flop_could", models.PositiveSmallIntegerField(default=0)),
                ("donk_flop_did", models.PositiveSmallIntegerField(default=0)),
                ("check_raise_could", models.PositiveSmallIntegerField(default=0)),
                ("check_raise_did", models.PositiveSmallIntegerField(default=0)),
                ("saw_flop_could", models.PositiveSmallIntegerField(default=0)),
                ("saw_flop_did", models.PositiveSmallIntegerField(default=0)),
                ("went_to_showdown_could", models.PositiveSmallIntegerField(default=0)),
                ("went_to_showdown_did", models.PositiveSmallIntegerField(default=0)),
                ("won_at_showdown_could", models.PositiveSmallIntegerField(default=0)),
                ("won_at_showdown_did", models.PositiveSmallIntegerField(default=0)),
                ("postflop_bets", models.PositiveSmallIntegerField(default=0)),
                ("postflop_raises", models.PositiveSmallIntegerField(default=0)),
                ("postflop_calls", models.PositiveSmallIntegerField(default=0)),
                ("postflop_checks", models.PositiveSmallIntegerField(default=0)),
                ("postflop_folds", models.PositiveSmallIntegerField(default=0)),
                ("invested_bb", models.FloatField(default=0)),
                ("net_bb", models.FloatField(default=0)),
                ("allin_street", models.CharField(blank=True, max_length=16)),
                ("extra", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name="hand",
            name="effective_bb",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hand",
            name="facts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="hand",
            name="hero_combo",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="hand",
            name="hero_first_action",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="hand",
            name="hero_m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hand",
            name="hero_situation",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="hand",
            name="players_dealt",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hand",
            name="pot_type",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name="hand",
            index=models.Index(fields=["user", "hero_combo"], name="hand_combo"),
        ),
        migrations.AddIndex(
            model_name="hand",
            index=models.Index(
                fields=["user", "hero_situation"], name="hand_situation"
            ),
        ),
        migrations.AddField(
            model_name="handplayer",
            name="hand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="hands.hand",
            ),
        ),
        migrations.AddField(
            model_name="handplayer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hand_players",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="handplayer",
            index=models.Index(
                fields=["user", "is_hero", "position"], name="hand_player_hero"
            ),
        ),
        migrations.AddIndex(
            model_name="handplayer",
            index=models.Index(fields=["user", "name"], name="hand_player_name"),
        ),
        migrations.AddConstraint(
            model_name="handplayer",
            constraint=models.UniqueConstraint(
                fields=("hand", "seat"), name="unique_seat_per_hand"
            ),
        ),
    ]
