# Generated by Django 6.1.1 on 2026-10-08 16:51

from django.db import migrations, models
from django.db.models.fields.json import KeyTextTransform
from django.db.models.functions import Cast, Coalesce


def copy_from_replay(apps, schema_editor):
    """Hands stored before the columns have the pot and the rake in `replay` alone: no reparse needed."""
    Hand = apps.get_model("hands", "Hand")

    def key(name):
        return Coalesce(Cast(KeyTextTransform(name, "replay"), models.BigIntegerField()), 0)

    Hand.objects.update(total_pot=key("total_pot"), rake=key("rake"))


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0003_hand_facts"),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="rake",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hand",
            name="total_pot",
            field=models.BigIntegerField(default=0),
        ),
        migrations.RunPython(copy_from_replay, migrations.RunPython.noop),
    ]
