# Generated by Django 6.1.1 on 2026-10-08 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0004_hand_rake"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HandNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("tag", "Tag"),
                            ("review", "Review"),
                            ("purpose", "Purpose"),
                        ],
                        max_length=16,
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=16)),
                ("bet", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("value", models.CharField(blank=True, max_length=32)),
                ("text", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "hand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="hands.hand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hand_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "kind", "value"], name="hand_note_value"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "note")),
                        fields=("hand", "street"),
                        name="one_note_per_street",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "tag")),
                        fields=("hand", "value"),
                        name="each_tag_once",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "review")),
                        fields=("hand",),
                        name="one_review_state",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "purpose")),
                        fields=("hand", "bet"),
                        name="one_purpose_per_bet",
                    ),
                ],
            },
        ),
    ]
