# Generated by Django 6.1.1 on 2026-10-08 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0005_hand_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="handplayer",
            name="first_raise_all_in",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="handplayer",
            name="open_bb",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="handplayer",
            name="open_limpers",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="handplayer",
            name="three_bet_callers",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="handplayer",
            name="three_bet_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CoachPresets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("values", models.JSONField(blank=True, default=dict)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
