# Generated by Django 6.1.1 on 2026-10-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0006_leak_checks"),
    ]

    operations = [
        migrations.AddField(
            model_name="handplayer",
            name="allin_equity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="handplayer",
            name="ev_net_bb",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
