# Generated by Django 6.1.1 on 2026-10-08 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0007_all_in_equity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="session_hour",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hand",
            name="tables_open",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("hands", models.PositiveIntegerField(default=0)),
                ("tables", models.PositiveSmallIntegerField(default=0)),
                ("most_tables", models.PositiveSmallIntegerField(default=0)),
                ("net_bb", models.FloatField(default=0)),
                ("net_bb_squares", models.FloatField(default=0)),
                ("ev_net_bb", models.FloatField(default=0)),
                ("biggest_pot_bb", models.FloatField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-start", "-id"),
            },
        ),
        migrations.AddField(
            model_name="hand",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hand_set",
                to="hands.session",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["user", "-start"], name="session_start"),
        ),
    ]
