# Generated by Django 6.1.1 on 2026-10-08 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0008_sessions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="handplayer",
            name="strong_fold_could",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="handplayer",
            name="strong_fold_did",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="handplayer",
            name="thin_value_could",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="handplayer",
            name="thin_value_did",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="HandBet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=64)),
                ("is_hero", models.BooleanField(default=False)),
                ("street", models.CharField(max_length=16)),
                ("order", models.PositiveSmallIntegerField()),
                ("kind", models.CharField(max_length=8)),
                ("amount_bb", models.FloatField()),
                ("pot_bb", models.FloatField()),
                ("size", models.FloatField(blank=True, null=True)),
                ("to_bb", models.FloatField()),
                ("opponents", models.PositiveSmallIntegerField()),
                ("all_in", models.BooleanField(default=False)),
                ("cbet", models.BooleanField(default=False)),
                ("made", models.CharField(blank=True, max_length=24)),
                (
                    "strength",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nothing", "Nothing"),
                            ("draw", "Draw"),
                            ("weak", "Weak"),
                            ("strong", "Strong"),
                            ("nuts", "Nuts"),
                        ],
                        max_length=8,
                    ),
                ),
                ("wetness", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("outcome", models.CharField(max_length=8)),
                ("hero_response", models.CharField(blank=True, max_length=8)),
                (
                    "hand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="hands.hand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hand_bets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_hero", "street"], name="hand_bet_street"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hand", "order"), name="unique_bet_order"
                    )
                ],
            },
        ),
    ]
