# Generated by Django 6.1.1 on 2026-10-08 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0009_hand_bets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(max_length=32)),
                ("tournament_id", models.CharField(max_length=32)),
                ("game", models.CharField(max_length=64)),
                ("hero", models.CharField(blank=True, max_length=64)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("play_money", models.BooleanField(default=False)),
                ("freeroll", models.BooleanField(default=False)),
                ("buy_in", models.BigIntegerField(default=0)),
                ("fee", models.BigIntegerField(default=0)),
                ("bounty", models.BigIntegerField(default=0)),
                ("first_hand", models.DateTimeField()),
                ("last_hand", models.DateTimeField()),
                ("hands", models.PositiveIntegerField(default=0)),
                ("max_seats", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("top_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("entries", models.PositiveSmallIntegerField(default=1)),
                ("finish", models.PositiveIntegerField(blank=True, null=True)),
                ("prize", models.BigIntegerField(blank=True, null=True)),
                ("bounties_won", models.BigIntegerField(default=0)),
                ("knockouts", models.PositiveIntegerField(default=0)),
                ("field_size", models.PositiveIntegerField(blank=True, null=True)),
                ("payouts", models.JSONField(blank=True, default=list)),
                ("entered_finish", models.PositiveIntegerField(blank=True, null=True)),
                ("entered_prize", models.BigIntegerField(blank=True, null=True)),
                (
                    "entered_entries",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-first_hand", "-id"),
                "indexes": [
                    models.Index(
                        fields=["user", "-first_hand"], name="tournament_start"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "site", "tournament_id"),
                        name="unique_tournament_per_user",
                    )
                ],
            },
        ),
    ]
