# Generated by Django 6.1.1 on 2026-10-08 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0010_tournaments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=64)),
                ("hands", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("counters", models.JSONField(blank=True, default=dict)),
                ("vpip", models.FloatField(blank=True, null=True)),
                ("pfr", models.FloatField(blank=True, null=True)),
                ("aggression", models.FloatField(blank=True, null=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tag", "Tag"),
                            ("lag", "Lag"),
                            ("rock", "Rock"),
                            ("station", "Station"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "manual_label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tag", "Tag"),
                            ("lag", "Lag"),
                            ("rock", "Rock"),
                            ("station", "Station"),
                        ],
                        max_length=8,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("shared_hands", models.PositiveIntegerField(default=0)),
                ("hero_net_bb", models.FloatField(default=0)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opponents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "-hands"], name="opponent_hands"),
                    models.Index(
                        fields=["user", "-last_seen"], name="opponent_last_seen"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "site", "name"), name="unique_opponent_per_user"
                    )
                ],
            },
        ),
    ]
