# Generated by Django 6.1.1 on 2026-10-08 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0013_leak_reviews"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HandShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=24, unique=True)),
                ("write_up", models.TextField(blank=True)),
                ("anonymize", models.BooleanField(default=True)),
                ("revoked", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created", "-id"),
            },
        ),
        migrations.AlterField(
            model_name="handnote",
            name="kind",
            field=models.CharField(
                choices=[
                    ("note", "Note"),
                    ("tag", "Tag"),
                    ("review", "Review"),
                    ("purpose", "Purpose"),
                    ("writeup", "Writeup"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="handnote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "writeup")),
                fields=("hand",),
                name="one_writeup_per_hand",
            ),
        ),
        migrations.AddField(
            model_name="handshare",
            name="hand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="hands.hand",
            ),
        ),
        migrations.AddField(
            model_name="handshare",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
