# Generated by Django 6.1.1 on 2026-10-08 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hands", "0003_hand_facts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeHand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("small_blind", models.PositiveIntegerField()),
                ("big_blind", models.PositiveIntegerField()),
                ("button_seat", models.PositiveSmallIntegerField()),
                ("stacks", models.JSONField()),
                ("deck", models.CharField(max_length=104)),
                ("moves", models.JSONField(default=list)),
                ("replay", models.JSONField(default=dict)),
                ("phh", models.TextField(blank=True)),
                ("finished", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("number",),
            },
        ),
        migrations.CreateModel(
            name="Playbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("game", models.CharField(max_length=64)),
                ("format", models.CharField(max_length=16)),
                ("description", models.TextField(blank=True)),
                ("rules", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoachedMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opponent",
                    models.CharField(
                        choices=[
                            ("mystery", "Mystery"),
                            ("tag", "Tight-aggressive"),
                            ("lag", "Loose-aggressive"),
                            ("station", "Calling station"),
                            ("rock", "Rock"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "coach",
                    models.CharField(
                        choices=[
                            ("progress", "Follow my progress"),
                            ("1", "Watch"),
                            ("2", "Call it"),
                            ("3", "Play, then hear it"),
                            ("4", "Solo"),
                        ],
                        default="progress",
                        max_length=16,
                    ),
                ),
                ("starting_bb", models.PositiveSmallIntegerField(default=40)),
                ("hands_planned", models.PositiveSmallIntegerField(default=30)),
                ("time_bank", models.FloatField(default=60)),
                ("result_bb", models.FloatField(blank=True, null=True)),
                ("expected_bb", models.FloatField(blank=True, null=True)),
                ("started", models.DateTimeField(auto_now_add=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "playbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="practice.playbook",
                    ),
                ),
            ],
            options={
                "ordering": ("-started",),
            },
        ),
        migrations.CreateModel(
            name="MatchDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.PositiveIntegerField()),
                ("context", models.JSONField()),
                ("advice", models.JSONField()),
                ("stage", models.PositiveSmallIntegerField()),
                ("intent", models.JSONField(blank=True, null=True)),
                ("move", models.JSONField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=16)),
                ("followed", models.BooleanField(null=True)),
                ("asked", models.BooleanField(default=False)),
                ("departure", models.CharField(blank=True, max_length=16)),
                ("time_taken", models.FloatField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="practice.coachedmatch",
                    ),
                ),
                (
                    "hand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="practice.practicehand",
                    ),
                ),
            ],
            options={
                "ordering": ("hand__number", "step"),
            },
        ),
        migrations.CreateModel(
            name="PracticeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seats", models.JSONField()),
                ("small_blind", models.PositiveIntegerField()),
                ("big_blind", models.PositiveIntegerField()),
                ("button_seat", models.PositiveSmallIntegerField()),
                ("hands_played", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_tables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="practicehand",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hands",
                to="practice.practicetable",
            ),
        ),
        migrations.AddField(
            model_name="coachedmatch",
            name="table",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match",
                to="practice.practicetable",
            ),
        ),
        migrations.CreateModel(
            name="ReadNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hand_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("showdown", "Showdown note"),
                            ("read", "Read"),
                            ("label", "Label"),
                        ],
                        max_length=16,
                    ),
                ),
                ("tag", models.CharField(max_length=32)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                (
                    "by",
                    models.CharField(
                        choices=[("coach", "Coach"), ("user", "You")], max_length=8
                    ),
                ),
                ("withdrawn", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_notes",
                        to="practice.coachedmatch",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="practice.readnote",
                    ),
                ),
            ],
            options={
                "ordering": ("created", "id"),
            },
        ),
        migrations.CreateModel(
            name="RuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("playbook_key", models.SlugField(max_length=64)),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("button", "Button play"),
                            ("out_of_position", "Out of position"),
                            ("sizing", "Sizing"),
                            ("showdown_value", "Showdown value and price"),
                            ("stack_depth", "Stack depth and all-ins"),
                            ("adjustments", "Adjustments"),
                        ],
                        max_length=24,
                    ),
                ),
                ("stage", models.PositiveSmallIntegerField(default=1)),
                ("recent", models.JSONField(default=list)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("own_hand", "One of your hands"),
                            ("generated", "Generated"),
                            ("match", "A coached match"),
                        ],
                        max_length=16,
                    ),
                ),
                ("step", models.PositiveIntegerField(blank=True, null=True)),
                ("topic", models.CharField(max_length=32)),
                ("origin", models.JSONField(blank=True, default=dict)),
                ("spec", models.JSONField()),
                ("answer", models.JSONField()),
                (
                    "grading",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("reference", "Reference range"),
                            ("rule", "Rule of thumb"),
                            ("reflection", "Reflection"),
                        ],
                        max_length=16,
                    ),
                ),
                ("skills", models.JSONField(default=list)),
                ("tier", models.PositiveSmallIntegerField(default=1)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "hand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="hands.hand",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("box", models.PositiveSmallIntegerField(default=1)),
                ("due", models.DateField()),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="practice.scenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScenarioSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("daily", "Today's set"),
                            ("my_hands", "My hands"),
                            ("generated", "Generated"),
                            ("match", "From a match"),
                        ],
                        max_length=16,
                    ),
                ),
                ("day", models.DateField()),
                ("skill", models.CharField(blank=True, max_length=32)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("action", models.CharField(blank=True, max_length=8)),
                ("amount", models.BigIntegerField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=16)),
                ("confidence", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("time_taken", models.FloatField(blank=True, null=True)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("acceptable", "Acceptable"),
                            ("poor", "Poor"),
                            ("ungraded", "Not graded"),
                        ],
                        max_length=12,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(default=1)),
                ("ev_lost_bb", models.FloatField(blank=True, null=True)),
                ("rule", models.CharField(blank=True, max_length=40)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="practice.scenario",
                    ),
                ),
                (
                    "set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="practice.scenarioset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("review", models.BooleanField(default=False)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="practice.scenario",
                    ),
                ),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="practice.scenarioset",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
            },
        ),
        migrations.AddField(
            model_name="scenarioset",
            name="scenarios",
            field=models.ManyToManyField(
                related_name="sets", through="practice.SetItem", to="practice.scenario"
            ),
        ),
        migrations.AddConstraint(
            model_name="playbook",
            constraint=models.UniqueConstraint(
                fields=("owner", "key", "version"), name="one_playbook_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchdecision",
            constraint=models.UniqueConstraint(
                fields=("hand", "step"), name="one_decision_per_step"
            ),
        ),
        migrations.AddConstraint(
            model_name="practicehand",
            constraint=models.UniqueConstraint(
                fields=("table", "number"), name="one_hand_per_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="ruleprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "playbook_key", "family"),
                name="one_progress_per_family",
            ),
        ),
        migrations.AddIndex(
            model_name="scenario",
            index=models.Index(fields=["source", "topic"], name="scenario_kind"),
        ),
        migrations.AddConstraint(
            model_name="scenario",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hand__isnull", False)),
                fields=("owner", "hand", "step", "topic"),
                name="one_scenario_per_decision_and_topic",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user", "due"], name="review_due"),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "scenario"), name="one_review_per_spot"
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(fields=["user", "-created"], name="attempt_recent"),
        ),
        migrations.AddConstraint(
            model_name="setitem",
            constraint=models.UniqueConstraint(
                fields=("set", "position"), name="one_spot_per_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="scenarioset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "daily")),
                fields=("user", "day"),
                name="one_daily_set_per_day",
            ),
        ),
    ]
