# Generated by Django 6.1.1 on 2026-10-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="hand_range",
            field=models.TextField(blank=True),
        ),
    ]
