# Generated by Django 6.1.1 on 2026-10-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_range_answers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="source",
            field=models.CharField(
                choices=[
                    ("own_hand", "One of your hands"),
                    ("generated", "Generated"),
                    ("match", "A coached match"),
                    ("library", "The library"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="scenarioset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("daily", "Today's set"),
                    ("my_hands", "My hands"),
                    ("generated", "Generated"),
                    ("match", "From a match"),
                    ("library", "The library"),
                ],
                max_length=16,
            ),
        ),
    ]
