# Generated by Django 6.1.1 on 2026-10-09 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_library"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="difficulty",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="difficulty_deviation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="rated",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scenarioset",
            name="planned",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenarioset",
            name="ratings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="scenarioset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("daily", "Today's set"),
                    ("my_hands", "My hands"),
                    ("generated", "Generated"),
                    ("match", "From a match"),
                    ("library", "The library"),
                    ("test", "Aptitude test"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="SkillScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=32)),
                ("rating", models.FloatField(default=1500)),
                ("deviation", models.FloatField(default=350)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("updated", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "skill"), name="one_score_per_skill"
                    )
                ],
            },
        ),
    ]
