# Generated by Django 6.1.1 on 2026-10-09 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0005_their_seat"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicehand",
            name="script",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="practicehand",
            name="script_board",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="practicehand",
            name="scripted",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="practicetable",
            name="ante",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="practicetable",
            name="currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="practicetable",
            name="kind",
            field=models.CharField(
                choices=[("match", "A coached match"), ("play", "Play it out")],
                default="match",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="practicetable",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="practice.scenario",
            ),
        ),
    ]
