# Generated by Django 6.1.1 on 2026-10-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0006_play_it_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbook",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
