# Generated by Django 6.1.1 on 2026-10-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0007_coach_playbooks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="source",
            field=models.CharField(
                choices=[
                    ("own_hand", "One of your hands"),
                    ("generated", "Generated"),
                    ("match", "A coached match"),
                    ("library", "The library"),
                    ("their_seat", "An opponent's seat in one of your hands"),
                    ("shared", "A hand shared with your class"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="scenarioset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("daily", "Today's set"),
                    ("my_hands", "My hands"),
                    ("generated", "Generated"),
                    ("match", "From a match"),
                    ("library", "The library"),
                    ("their_seat", "Their seat"),
                    ("shared", "From your classes"),
                    ("test", "Aptitude test"),
                ],
                max_length=16,
            ),
        ),
    ]
