from django.urls import path

from .views import (
    UserEmailLoginAPIView,
    UserEmailSignupAPIView,
    MyProfileAPIView,
    MyProfileUpdateAPIView,
    UserLogoutAPIView,
    UserEmailSendConfirmCodeAPIView,
    UserEmailCheckConfirmCodeAPIView,
    CreatorProfileAPIView,
    UserFindPwEmailSendConfirmCodeAPIView,
    UserFindPwEmailCheckConfirmCodeAPIView,
    UserEmailResetPwAPIView,
    UserEmailAvailabilityAPIView,
    UserTagAvailabilityAPIView,
    UserTagUpdateAPIView,
    UserDeleteAccountAPIView,
    UserRecoverAccountAPIView,
    UserProfileAPIView,
    UserSocialCheckAPIView,
    UserSocialSignupAPIView,
    UserSocialSigninAPIView,
    UserBlockAPIView,
    UserUnblockAPIView,
    BlockedUsersAPIView,
)

urlpatterns = [
    # 사용자 공통 api
    path(
        "user/my_profile",
        MyProfileAPIView.as_view(),
        name="user-my-profile",
    ),
    path(
        "user/my_profile/update",
        MyProfileUpdateAPIView.as_view(),
        name="user-my-profile-update",
    ),
    path(
        "user/user_tag/update",
        UserTagUpdateAPIView.as_view(),
        name="user-tag-update",
    ),
    path(
        "user/creator/<str:user_tag>/profile",
        CreatorProfileAPIView.as_view(),
        name="user-creator-profile",
    ),
    path(
        "user/login/email",
        UserEmailLoginAPIView.as_view(),
        name="user-login-email",
    ),
    path(
        "user/logout",
        UserLogoutAPIView.as_view(),
        name="user-logout",
    ),
    # TODO - 아래 2개 api 에 대해서 테스트 코드 작성
    path(
        "user/signup/email/send_confirm_code",
        UserEmailSendConfirmCodeAPIView.as_view(),
        name="user-signup-email-send-confirm-code",
    ),
    path(
        "user/signup/email/check_confirm_code",
        UserEmailCheckConfirmCodeAPIView.as_view(),
        name="user-signup-email-check-confirm-code",
    ),
    # 고객용 api
    path(
        "user/signup/email",
        UserEmailSignupAPIView.as_view(),
        name="user-signup-email",
    ),
    path(
        "user/find_pw/email/send_confirm_code",
        UserFindPwEmailSendConfirmCodeAPIView.as_view(),
        name="user-find-pw-email-send-confirm-code",
    ),
    path(
        "user/find_pw/email/check_confirm_code",
        UserFindPwEmailCheckConfirmCodeAPIView.as_view(),
        name="user-find-pw-email-check-confirm-code",
    ),
    path(
        "user/email/reset_pw",
        UserEmailResetPwAPIView.as_view(),
        name="user-email-reset-pw",
    ),
    path(
        "user/delete_account",
        UserDeleteAccountAPIView.as_view(),
        name="user-delete-account",
    ),
    path(
        "user/recover_account",
        UserRecoverAccountAPIView.as_view(),
        name="user-recover-account",
    ),
    # 회원가입 관련 가용성 검증 API
    path(
        "user/signup/check_email",
        UserEmailAvailabilityAPIView.as_view(),
        name="user-signup-check-email",
    ),
    path(
        "user/signup/check_user_tag",
        UserTagAvailabilityAPIView.as_view(),
        name="user-signup-check-user-tag",
    ),
    path(
        "user/<str:user_tag>/profile",
        UserProfileAPIView.as_view(),
        name="user-profile",
    ),
    path(
        "user/social/check",
        UserSocialCheckAPIView.as_view(),
        name="user-social-check",
    ),
    path(
        "user/social/signup",
        UserSocialSignupAPIView.as_view(),
        name="user-social-signup",
    ),
    path(
        "user/social/signin",
        UserSocialSigninAPIView.as_view(),
        name="user-social-signin",
    ),
    # 사용자 차단 API
    path(
        "user/<str:user_tag>/block",
        UserBlockAPIView.as_view(),
        name="user-block",
    ),
    path(
        "user/<str:user_tag>/unblock",
        UserUnblockAPIView.as_view(),
        name="user-unblock",
    ),
    path(
        "user/blocked_users",
        BlockedUsersAPIView.as_view(),
        name="user-blocked-users",
    ),
]
