from django.urls import path

from .views import (
    MyProfileAPIView,
    MyProfileUpdateAPIView,
    UserDeleteAccountAPIView,
    UserEmailAvailabilityAPIView,
    UserEmailCheckConfirmCodeAPIView,
    UserEmailLoginAPIView,
    UserEmailResetPwAPIView,
    UserEmailSendConfirmCodeAPIView,
    UserEmailSignupAPIView,
    UserFindPwEmailCheckConfirmCodeAPIView,
    UserFindPwEmailSendConfirmCodeAPIView,
    UserLogoutAPIView,
    UserProfileAPIView,
    UserRecoverAccountAPIView,
    UserSocialCheckAPIView,
    UserSocialSigninAPIView,
    UserSocialSignupAPIView,
    UserTagAvailabilityAPIView,
    UserTagUpdateAPIView,
)

urlpatterns = [
    # Common user APIs
    path(
        "user/my-profile",
        MyProfileAPIView.as_view(),
        name="user-my-profile",
    ),
    path(
        "user/my-profile/update",
        MyProfileUpdateAPIView.as_view(),
        name="user-my-profile-update",
    ),
    path(
        "user/username/update",
        UserTagUpdateAPIView.as_view(),
        name="user-tag-update",
    ),
    path(
        "user/login/email",
        UserEmailLoginAPIView.as_view(),
        name="user-login-email",
    ),
    path(
        "user/logout",
        UserLogoutAPIView.as_view(),
        name="user-logout",
    ),
    path(
        "user/signup/email/send-confirm-code",
        UserEmailSendConfirmCodeAPIView.as_view(),
        name="user-signup-email-send-confirm-code",
    ),
    path(
        "user/signup/email/check-confirm-code",
        UserEmailCheckConfirmCodeAPIView.as_view(),
        name="user-signup-email-check-confirm-code",
    ),
    # Customer APIs
    path(
        "user/signup/email",
        UserEmailSignupAPIView.as_view(),
        name="user-signup-email",
    ),
    path(
        "user/find-pw/email/send-confirm-code",
        UserFindPwEmailSendConfirmCodeAPIView.as_view(),
        name="user-find-pw-email-send-confirm-code",
    ),
    path(
        "user/find-pw/email/check-confirm-code",
        UserFindPwEmailCheckConfirmCodeAPIView.as_view(),
        name="user-find-pw-email-check-confirm-code",
    ),
    path(
        "user/email/reset-pw",
        UserEmailResetPwAPIView.as_view(),
        name="user-email-reset-pw",
    ),
    path(
        "user/delete-account",
        UserDeleteAccountAPIView.as_view(),
        name="user-delete-account",
    ),
    path(
        "user/recover-account",
        UserRecoverAccountAPIView.as_view(),
        name="user-recover-account",
    ),
    # Signup-related availability check APIs
    path(
        "user/signup/check-email",
        UserEmailAvailabilityAPIView.as_view(),
        name="user-signup-check-email",
    ),
    path(
        "user/signup/check-username",
        UserTagAvailabilityAPIView.as_view(),
        name="user-signup-check-user-tag",
    ),
    path(
        "user/<str:username>/profile",
        UserProfileAPIView.as_view(),
        name="user-profile",
    ),
    path(
        "user/social/check",
        UserSocialCheckAPIView.as_view(),
        name="user-social-check",
    ),
    path(
        "user/social/signup",
        UserSocialSignupAPIView.as_view(),
        name="user-social-signup",
    ),
    path(
        "user/social/signin",
        UserSocialSigninAPIView.as_view(),
        name="user-social-signin",
    ),
]
