# Generated by Django 6.1.1 on 2026-10-04 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stream_id", models.UUIDField()),
                ("source", models.CharField(max_length=32)),
                ("platform", models.CharField(max_length=16)),
                ("client_version", models.CharField(max_length=32)),
                ("path_hint", models.CharField(blank=True, max_length=512)),
                ("fingerprint", models.CharField(max_length=64)),
                ("acked_offset", models.BigIntegerField(default=0)),
                ("parsed_offset", models.BigIntegerField(default=0)),
                ("parser_state", models.JSONField(blank=True, default=dict)),
                ("parser_version", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("last_chunk_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_streams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_offset", models.BigIntegerField()),
                ("end_offset", models.BigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("compressed_size", models.PositiveIntegerField()),
                ("storage_key", models.CharField(max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="tracker.logstream",
                    ),
                ),
            ],
            options={
                "ordering": ("start_offset",),
            },
        ),
        migrations.AddConstraint(
            model_name="logstream",
            constraint=models.UniqueConstraint(fields=("user", "stream_id"), name="unique_stream_per_user"),
        ),
        migrations.AddConstraint(
            model_name="logchunk",
            constraint=models.UniqueConstraint(fields=("stream", "start_offset"), name="unique_chunk_start_per_stream"),
        ),
    ]
