# Generated by Django 6.0.5 on 2026-05-24 21:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, verbose_name='Auth token')),
                ('client', models.CharField(max_length=50, verbose_name='Client source')),
                ('client_version', models.CharField(max_length=20, verbose_name='Client version')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Client submitted at')),
                ('payload', models.JSONField(verbose_name='Raw error payload')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Server received at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_errorlog_created'), models.Index(fields=['token'], name='idx_errorlog_token')],
            },
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, verbose_name='Auth token')),
                ('client', models.CharField(max_length=50, verbose_name='Client source')),
                ('client_version', models.CharField(max_length=20, verbose_name='Client version')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Client submitted at')),
                ('payload', models.JSONField(verbose_name='Raw game payload')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Server received at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_gamelog_created'), models.Index(fields=['token'], name='idx_gamelog_token')],
            },
        ),
    ]
