# Generated by Django 6.0.5 on 2026-06-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokerlogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamelog",
            old_name="token",
            new_name="client_token_hash",
        ),
    ]
