# Generated by Django 6.0.5 on 2026-06-03 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokerlogs", "0002_rename_token_gamelog_client_token_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="gamelog",
            name="idx_gamelog_token",
        ),
        migrations.AddIndex(
            model_name="gamelog",
            index=models.Index(
                fields=["client_token_hash"], name="idx_gamelog_client_token_hash"
            ),
        ),
    ]
